name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore ReSharperCleanupCodeDemo.sln

    - name: Cleanup Code
      id: cleanup
      uses: ArturWincenciak/ReSharper_CleanupCode@v2.0
      with:
        solution: 'UnityPrototype4.sln'
        fail_on_reformat_needed: 'no'
        auto_commit: 'yes'
        jb_cleanup_code_arg: '--verbosity=INFO --profile=Almost Full Cleanup --Include=**Assets/Scripts/**.*'
        commit_message: 'Cleanup code by ReSharper'
        commit_creator_email: 'cleanupcode@github.action'
        commit_creator_name: 'CleanupCode Action'
